# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
branches:
  only:
  - master
  - /release-.*/
  - /v(\d+)\.(\d+)\.(\d+)/
codecov: true
jobs:
  include:
    - os: windows
      arch: x86
      julia: 1.0
      name: "Julia: 1.0 (32bit)"
    - os: windows
      arch: x86
      julia: 1.1
      name: "Julia: 1.1 (32bit)"
    - os: windows
      arch: x86
      julia: 1.2
      name: "Julia: 1.2 (32bit)"
    - os: windows
      arch: x86
      julia: 1.3
      name: "Julia: 1.3 (32bit)"
    - os: windows
      arch: x86
      julia: nightly
      name: "Julia: nightly (32bit)"
